spring:
  cloud: 
    bus:
      enabled: false
      
logging:
  level:    
    root: debug
    com.msdemo.v2: trace
    com.github.tobato.fastdfs: debug
    org.springframework.jms.connection.JmsTransactionManager: debug
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    org.springframework.data.mongodb.MongoTransactionManager: debug
    com.alibaba.druid: debug

fdfs:
  soTimeout: 1500
  connectionTimeout: 600
  trackerList:
    - centos:22122   
#fdfs:
#  soTimeout: 1500 #socket连接超时时长
#  connectTimeout: 600 #连接tracker服务器超时时长
##  reqHost: 192.168.8.101   #nginx访问地址
##  reqPort: 80              #nginx访问端口
#  thumb-image: #缩略图生成参数，可选
#    width: 150
#    height: 150
#  trackerList: 
#    - centos:22122
msdemo-config:      
  performance:
    sql-cost: true
  debug:  
    sql-param: false      